#!/bin/bash
# Author: Lara Maia
# Version: 0.1

pv_md5=`md5sum "$2" || echo 0`
ps_md5=0

case $3 in
	-c) cat "$1" | xxd -ps >> "$2" && ps_md5=`md5sum "$2"`;;
	-d) cat "$1" | xxd -r -p > "$2" && ps_md5=`md5sum "$2"` ;;
	-ds) cat "$1" | xxd -r -p ;;
esac

echo -e "\nPV: ${pv_md5%% *}\nPS: ${ps_md5%% *}\n"

