#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Converte arquivos binários em hexadecimal
# e arquivos hexadecimais em binário
# Lara Maia <lara@craft.net.br> © 2013 :c)
# Versão: 0.1

import binascii
import sys

try:
  if (sys.argv[1] == "--tohex"):
    arquivo = sys.argv[2]
    with open(arquivo, 'rb') as f:
      conteudo = f.read()
    with open(sys.argv[3], 'w') as d:
      c = 80
      while c <= len(binascii.hexlify(conteudo)):
        d.write(binascii.hexlify(conteudo)[(c-80):c] + "\n")
        c += 80
  elif (sys.argv[1] == "--tobin"):
    arquivo = sys.argv[2]
    with open(arquivo, 'rb') as f:
      conteudo = f.read()
    with open(sys.argv[3], 'w') as d:
      conteudo = conteudo.replace('\n', '')
      d.write(binascii.unhexlify(conteudo))
  else:
    raise
except:
  print('uso: --tohex <binário> <saida>')
  print('     --tobin <hexa>    <saida>')
  
exit(0)
