#!/bin/bash
# Lara Maia <lara@craft.net.br> © 2013 :c)
# Need icoutils

test "$1" == "" && exit 1

for icon in $(wrestool -l "$1" | grep group_icon | awk '{print $2}' | cut -f2 -d=); do
	file="$(basename -zs'.exe' "$1")-$icon.ico"
	echo "Extraindo $file"
	wrestool -x -n $icon "$1" > "$file"
done
