#!/bin/sh
# Speedup kde login
# Author: Lara Maia
# Version: 0.1

ENABLE_KSPLASHX=true

export KDEHOME=$HOME/.kde4
export QT_PLUGIN_PATH=/usr/lib/kde4/plugins/

#[ -r $kdehome/share/config/startupconfig ] && . $kdehome/share/config/startupconfig

for file in "${KDEHOME}/env/"; do
    test -r "$file" && . "$file"
done

(LD_BIND_NOW=true /usr/lib/kde4/libexec/start_kdeinit_wrapper +kcminit_startup) &

if [ "$ENABLE_KSPLASHX" == "true" ]; then
    . $KDEHOME/share/config/ksplashrc
    ksplashx_pid=`ksplashx "${Theme}" --pid`
fi

plasma-desktop
#plasma-netbook
/usr/lib/kde4/libexec/polkit-kde-authentication-agent-1

kill $ksplashx_pid

(sleep 3
klipper
kmix
kmixctrl --restore
krunner) &

kwin

kdeinit4_shutdown
