#!/bin/bash
# Define a frequencia da cpu
# Autor: Lara Maia
# Versão: 0.1
# INFO:
#      $1 = núcleo (ou all)
#      $2 = min | max

if [ `id -u` != 0 ]; then
  echo "Este script deve ser executado como ROOT!"
  exit 1
fi

case $2 in
        min) freq=ondemand ;;
        max) freq=performance ;;
esac

if [ "$1" != "all" ]; then
  cpufreq-set -c $1 -g $freq
else
  nucleos=`cat /proc/cpuinfo | grep process | wc -l`
  i=0; while [ $i -lt $nucleos ]; do
    cpufreq-set -c $i -g $freq
  ((i+=1)); done
fi

echo "Aguarde..."; sleep 3
cpufreq-info | grep "o CPU"

exit 0
