#!/bin/bash
# Define a frequencia da cpu
# Lara Maia <lara@craft.net.br>
# Versão: 1.0
# INFO:
#      $1 = núcleo (ou all)
#      $2 = min | max | auto
# --------------------------
# Depends:
# cpupower

if [ `id -u` != 0 ]; then
  echo "Este script deve ser executado como ROOT!"
  exit 1
fi

case $2 in
        min) freq=powersave ;;
        max) freq=performance ;;
        auto) freq=ondemand ;;
esac

if [ "$1" != "all" ]; then
  cpupower -c $1 frequency-set -g $freq
  cpupower -c $1 frequency-info | grep "o CPU"
else
  nucleos=`cat /proc/cpuinfo | grep process | wc -l`
  i=0; while [ $i -lt $nucleos ]; do
    cpupower -c $i frequency-set -g $freq
    cpupower -c $i frequency-info | grep "o CPU"
  ((i+=1)); done
fi

exit 0
