#!/bin/bash
# Upload semi-automático ao launchpad
# Autor: Lara Maia | Versão: 0.6
# Ultima modificação: Tue, 08 Nov 2011 08:23:28 -0200

# $1 = pacote | $2 = versão | $3 = build | $4 = ppa

rm ../*.build ../*.changes ../*.upload ../*.dsc ../*.diff.gz
#dpkg-source -b ../rof
#mv ${1}_${2}-${3}.tar.gz ../${1}_${2}.orig.tar.gz
#rm *.dsc
debuild -S
dput ppa:mrk3004/${4} ../${1}_${2}-${3}_source.changes

