#!/bin/bash
# Scripts de desligamento para o openbox+systemd
# Autor: Lara Maia <lara@craft.net.br>

function msg() {
# $1 = text
# $2 = command
	if [ "${DESKTOP_SESSION%%-*}" == "kde" ]; then
		kdialog -warningyesno "$1" --title="${1##*mesmo}"
	else
		yad --button=Não:1 --button=Sim:0 --image=dialog-question \
		    --title="${1##*mesmo}" --window-icon=important \
		    --text "${1}"
	fi
	
	if [ $? == 0 ]; then
		if [ "$2" == "logout" ]; then
			gksu -m "Você precisa de acesso de administrador\
			para fazer isso. Digite sua senha abaixo:" killall xinit
		else
			sudo systemctl ${2}
		fi
	fi
}

case $1 in
	desligar) msg "Você quer mesmo desligar o computador?" poweroff ;;
	reiniciar) msg "Você quer mesmo reiniciar o computador?" reboot ;;
	espera) msg "Você quer mesmo colocar o computador em espera?" suspend ;;
	hibernar) msg "Você quer mesmo hibernar o computador?" hibernate ;;
	logout) msg "Você quer mesmo encerrar sua sessão?" logout ;;
esac

exit 0
