#!/bin/bash

windows=(`wmctrl -l | awk '{print $1}'`)

case $1 in
	0) for window in ${windows[@]}; do
           wmctrl -i -r $window -b remove,hidden
       done
       ;;
	1) for window in ${windows[@]}; do
           wmctrl -i -r $window -b add,hidden
       done
       wmctrl -a tilda
       ;;
esac

unset windows
exit 0
