#!/bin/bash
# Versão: 0.7 Beta
# Autor: Lara Maia
# Ultima atualização: 12/02/2012
# Acelerador de downloads para o slapt-get
# Versão para slapt-get em PT_BR e EN
# Modo: Unix (LF) | Codificação: UTF-8

# checa opções e faz rebuild dos parâmetros
c=2; for param in $@; do
  if [ $param == "--conex" ]; then
    conex=`eval echo $'$'$c`
    pp=true
  else
    if [ ! $pp ]; then
      argvs[$[$c-2]]=`eval echo $'$'$[$c-1]`
    else
      unset pp
    fi
  fi
c=$[$c+1]; done
if [ "$conex" == "" ]; then conex=8; fi

function check_conflits {
  if [ "$1" = "printmsgerror" ]; then
    echo -e "Parâmetros incorretos! digite \033[01mslapt-fast help\033[m para obter ajuda"
    exit 1
  fi
  for param in $@; do
    case $param in
      -s|-d|-S|-c|-y|-p|simulate|download-only|print-uris|show-stats|config|retry|no-upgrade|prompt|no-prompt)
      echo -e "A opção $param não é suportada\nAbortar!"
      exit 1
      ;;
      --simulate|--download-only|--print-uris|--show-stats|--config|--retry|--no-upgrade|--prompt|--no-prompt)
      echo -e "A opção $param não é suportada\nAbortar!"
      exit 1
      ;;
    esac
  done
}

# Checa se possui privilégios apropriados
if [ "$(id -u)" != "0" ]; then
  echo "Esse script deve ser executado como super usuário (root ou sudo)."
  exit
fi

# Testa se o axel está instalado
if [ ! -f /usr/local/bin/axel ] && [ ! -f /usr/bin/axel ]; then
echo "A dependência Axel necessária para execução do script não foi encontrada."
echo "Está disponível no seguinte link: http://alioth.debian.org/projects/axel/"
exit 1
fi

# Checa os comandos repassados ao script
if [ $# == 0 ]; then check_conflits printmsgerror; fi
for param in ${argvs[@]}; do
  if [ "$param" == "update" ]; then
    testupgrade=false; break
  fi
done
if [ "$testupgrade" != "false" ]; then
  slapt-get -s --${argvs[@]} 2>&1 | grep no-upgrade >/dev/null 2>&1
  if [ $? == 0 ] && [ $1 != "help" ]; then check_conflits printmsgerror; fi
fi
check_conflits $@

case $1 in
  --*)
  echo "Use comandos sem prefixo. Exemplo: slapt-fast help"
  exit 2
  ;;
  install|upgrade)
  # Recria pastas de cache se não existir
  if [ ! -d /var/cache/slapt-fast ]; then
    mkdir /var/cache/slapt-fast >/dev/null 2>&1
  fi
  if [ ! -d /var/cache/slapt-fast/packages/ ]; then
    mkdir /var/cache/slapt-fast/packages/ >/dev/null 2>&1
  fi

  # Mostra operação requisitada na tela
  slapt-get -s --${argvs[@]} | sed 's/Concluído//g' | sed 's/Done//g'

  # FIXME
  slapt-get -s --${argvs[@]} >/dev/null 2>&1 || exit 1
  slapt-get -s --${argvs[@]} | grep 'está atualizado' >/dev/null 2>&1 && exit 0
  slapt-get -s --${argvs[@]} | grep 'is up to date' >/dev/null 2>&1 && exit 0

  # Espera por ação do usuário
  echo -n "Continuar? [Y/n] "; read resp
  case $resp in n|N)
    echo "Abortar!" ; exit 0 ;;
  esac

  # Faz uma lista de pacotes e dependências a baixar
  slapt-get --print-uris --${argvs[@]} | egrep -o -e "(ht|f)tp://[^\']+" > /var/cache/slapt-fast/slapt-fast.list

  # Baixa pacotes em paralelo (que não estão no cache)
  for pacote in `cat /var/cache/slapt-fast/slapt-fast.list`; do
    set -- $pacote; IFS='/'; declare -a pkgn=($*)
    if [ ! -f /var/cache/slapt-fast/packages/${pkgn[$[${#pkgn[*]}-1]]} ]; then
      axel -a -n $conex --output=/var/cache/slapt-fast/packages "$pacote"
    fi
    unset pkgn
  done

  # instala pacotes que estão na lista de requisitados
  for pacote in `cat /var/cache/slapt-fast/slapt-fast.list`; do
    pkgn=`echo $pacote | grep txz`
    if [ "$pkgn" != "" ]; then
      installpkg /var/cache/slapt-fast/packages/$pkgn
    fi
  done
  ;;
  clean)
  echo "Apagando cache... "
  rm -rfv /var/cache/slapt-fast/
  echo "Concluído!"
  ;;
  update|remove|show|filelist)
  slapt-get --${argvs[@]}
  ;;
  search)
  echo "Procurando...."
  if [ "`slapt-get -s --$@`" == "" ]; then
    echo "Pacote não encontrado."
  else
    slapt-get --${argvs[@]}
  fi
  ;;
  *dist-upgrade*|*remove-obsolete*)
  echo -e "\n Este comando foi bloqueado no slapt-fast, pois se mostrou prejudicial na"
  echo "maioria das vezes, principalmente quando se usa sources de 'terceiros'. Caso"
  echo "queira atualizar seus pacotes, use apenas 'upgrade' ou consulte as instruções"
  echo "de atualização de versão no site ou fórum de sua distro."
  echo -e "\n Caso ainda queira insistir nesse parâmetro, ultilize o slapt-get "
  echo "diretamente, pois não mantenho suporte a comandos duvidosos, e nem aconselho "
  echo -e "os utilizadores de meus programas usar. Faça por sua própria conta e risco.\n"
  exit 2
  ;;
  help)
  echo $'''
slapt-fast - Lara Maia <lara@craft.net.br>
Um acelerador de downloads para o slapt-get

Utilização:
 slapt-fast [parâmetro(s)] <opções> [pacote(s)]

Parâmetros:
  update               Atualiza lista de pacotes
  upgrade              Atualiza pacotes instalados
  install  <pacote>    Instala pacote(s)
  remove   <pacote>    Remove pacote(s)
  clean                Apaga cache local de pacotes do slapt-fast
  show     <pacote>    Mostra informações sobre pacote(s)
  filelist <pacote>    Mostra arquivos intalados pelo(s) pacote(s)
  search   <pacote>    Procura por pacotes disponíveis

  help        Mostra essa ajuda

Opções:
  --ignore-excludes   instalar/atualizar excluídos
  --conex <número>    Número de conexões simultâneas (padrão 8)
  --no-md5            não validar soma md5
  --no-dep            ignorando verificação de dependência
  --ignore-dep        ignorar falhas de dependência
  --remove-obsolete   remove pacotes obsoletos
  '''
  ;;
  *)
  echo -n "Comando desconhecido ou ainda não implementado. Tentar com slapt-get? [S/n] "
  read resp; case $resp in n|N) echo "Abortar!" ; exit 0 ;; esac
  slapt-get ${argvs[@]}
  ;;
esac
exit 0
