#!/bin/bash
# Script para mudança de módulos de som
# Autor: Lara Maia
# Versão 0.4
# ----------------------------

printf "Mudar para: "
read resposta
if [ $resposta == "alsa" ]; then

	# While infinito até conseguir parar oss e carregar o alsa
	while true; do
		# Termina serviços e programas problemáticos
		killall -9 python knotify4 xfce4-volumed indicator-usb plugin-container 
		
		# Tenta parar oss 
		#/etc/init.d/oss stop 
		/etc/init.d/oss4-base stop 
		
		# Checa se obteve sucesso
		# Caso negativo, tenta fechar os processos
		# abertos que estão ultilizando a placa
		if [ $? != 0 ]; then
			#kill `/etc/init.d/oss stop | grep ^[0-9] | awk '{print $1}'` 
			kill `/etc/init.d/oss4-base stop | grep ^[0-9] | awk '{print $1}'` 
		else
			# Caso positivo desativa o oss (temporariamente)
			#/etc/init.d/oss unload 
			/etc/init.d/oss4-base force-unload 
			
			# Carrega módulo de som
			modprobe snd-cs4281 
			
			# Reinicia o alsa
			alsa force-reload 
			
			# Para while
			break
		fi
	done
	# Desativa encaminhamento virtual de mixers
	echo > /etc/asound
fi

if [ $resposta == "oss" ]; then
	# Termina serviços e programas problematicos
	killall -9 alsamixer pulseaudio

	# Desativa o alsa (permanente. A não ser que o script
	# seja executado novamente e a escolha seja 'alsa' )
	alsa force-unload 

	# Carrega módulo de som
	modprobe oss_cs4281
	
	# Carrega oss
	#/etc/init.d/oss start 
	/etc/init.d/oss4-base start
	/etc/init.d/oss4-base force-reload
	
	# Ativa encaminhamento virtual de mixers
	echo $'pcm.oss {
        type oss
        device /dev/dsp
}

pcm.!default {
        type oss
        device /dev/dsp
}

ctl.oss {
        type oss
        device /dev/mixer
}

ctl.!default {
        type oss
        device /dev/mixer
}
' > /etc/asound
	
	# Carrega aplicativos
	xfce4-volumed  &
	indicator-usb  &
	pyvolwheel  &
fi

exit 0
