#!/bin/bash
# Script para mudança de módulos de som
# Autor: Lara Maia
# Versão 0.2
# ----------------------------

modulo="snd-cs4281"

printf "Mudar para: "
read resposta
if [ $resposta == "alsa" ]; then

	# While infinito até conseguir parar oss e carregar o alsa
	while true; do
		# Termina serviços e programas problemáticos
		killall -9 python knotify4 xfce4-volumed indicator-usb plugin-container >/dev/null 2>&1
		
		# Tenta parar oss 
		/etc/init.d/oss stop >/dev/null 2>&1
		/etc/init.d/oss4-base stop >/dev/null 2>&1
		
		# Checa se obteve sucesso
		# Caso negativo, tenta fechar os processos
		# abertos que estão ultilizando a placa
		if [ $? != 0 ]; then
			kill `/etc/init.d/oss stop | grep ^[0-9] | awk '{print $1}'` >/dev/null 2>&1
			kill `/etc/init.d/oss4-base stop | grep ^[0-9] | awk '{print $1}'` >/dev/null 2>&1
		else
			# Caso positivo desativa o oss (temporariamente)
			/etc/init.d/oss unload >/dev/null 2>&1
			/etc/init.d/oss4-base unload >/dev/null 2>&1
			
			# Carrega módulo de som
			modprobe snd-cs4281 >/dev/null 2>&1
			
			# Reinicia o alsa
			alsa force-reload >/dev/null 2>&1
			
			# Para while
			break
		fi
	done
fi

if [ $resposta == "oss" ]; then
	# Desativa o alsa (permanente. A não ser que o script
	# seja executado novamente e a escolha seja 'alsa' )
	alsa unload 

	# Carrega módulo de som
	modprobe oss_cs4281
	
	# Carrega oss
	/etc/init.d/oss start 
	/etc/init.d/oss4-base start
	
	# Carrega aplicativos
	xfce4-volumed >/dev/null 2>&1 &
	indicator-usb >/dev/null 2>&1 &
	pyvolwheel >/dev/null 2>&1 &
fi

exit 0
