#!/bin/bash
# Lara Maia <lara@craft.net.br> 2015

function check() {
    if [ $1 == 0 ]; then
        echo -n "Normal "
    else
        echo -n "Offline "
    fi
}

function speed() {
    network=/sys/class/net/$1/statistics/$2
    sleep=1
    max=$3
    
    first=`cat $network` && sleep $sleep && end=`cat $network`
    BPS=$(( (((end-first)/sleep)*100)/max ))
    test $BPS -gt 100 && BPS=100
    
    echo $BPS
}

case $1 in
    net)     ping -c1 -w1 192.168.100.1 >/dev/null 2>&1 ; check $? ;;
    rede)    ping -c1 -w1 192.168.1.1 >/dev/null 2>&1   ; check $? ;;
    wifi)    ping -c1 -w1 192.168.1.2 >/dev/null 2>&1   ; check $? ;;
    dns)     ping -c1 -w1 google.com >/dev/null 2>&1    ; check $? ;;
    downbar) speed $2 rx_bytes $3 ;;
    upbar)   speed $2 tx_bytes $3 ;;
esac

exit 0
